Clean up installer and run scripts

diff --git a/hammerdb/install-script b/hammerdb/install-script
--- a/hammerdb/install-script
+++ b/hammerdb/install-script
@@ -20,10 +20,10 @@
 #
 # Script to set the system up for running hammerdb.
 #
-disks=none
-mountpoint=none
-db_type=none
-log_mount_point="none"
+disks=
+mountpoint=
+db_type=
+log_mount_point=
 
 install_mssql()
 {
@@ -32,50 +32,50 @@ install_mssql()
 	curl https://packages.microsoft.com/config/rhel/7/prod.repo > /etc/yum.repos.d/msprod.repo
 	yum -y remove unixODBC-utf16 unixODBC-utf16-devel
 	ACCEPT_EULA=Y yum install -y mssql-tools unixODBC-devel
+	# shellcheck disable=SC2016
 	echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
-	cd /usr/local/HammerDB
+	cd /usr/local/HammerDB || fatal "Cannot cd /usr/local/hammerdb"
 	cp -R  /tmp/hammerdb-tpcc/mssql/* .
 
 
-	rm -rf ${mountpoint}/mssql_data/*
-	mkdir -p ${mountpoint}/mssql_data
-	chown -R mssql:mssql ${mountpoint}/mssql_data 
-	chown -R mssql:mssql /perf1/mssql_data
+	rm -rf "${mountpoint}"/mssql_data/
+	mkdir -p "${mountpoint}"/mssql_data
+	chown -R mssql:mssql "${mountpoint}"/mssql_data 
 	
 	systemctl stop mssql-server
 
-	cd /opt/mssql/bin/
+	cd /opt/mssql/bin/ || fatal "Cannot cd /opt/mssql/bin"
 	mkdir /var/opt/mssql/secrets/
 
 	MSSQL_SA_PASSWORD="100yard-"
 	export MSSQL_SA_PASSWORD
-    export MSSQL_PID="Evaluation"
+	export MSSQL_PID="Evaluation"
 
 	rm -rf /var/opt/mssql
 	chmod 777 /var/opt
 
-	echo 1 > input
-	echo Yes >> input
-	echo 100yard- >> input
-	echo 100yard- >> input
-
-	./mssql-conf -n setup accept-eula < input
+	./mssql-conf -n setup accept-eula <<'EOF'
+1
+Yes
+100yard-
+100yard-
+EOF
 
 	sleep 30
 	systemctl stop mssql-server
 
-	cd /var/opt/mssql
-	mv data ${mountpoint}/mssql_data
-	ln -sf ${mountpoint}/mssql_data/data .
+	cd /var/opt/mssql || fatal "Cannot cd /var/opt/mssql"
+	mv data "${mountpoint}"/mssql_data
+	ln -sf "${mountpoint}"/mssql_data/data .
 
 	systemctl disable mssql-server.service
 	systemctl restart mssql-server.service
 
-	cd /usr/local/HammerDB
+	cd /usr/local/HammerDB || fatal "Cannot cd /usr/local/hammerdb"
 
-	./createdb_mssql_mnt.sh -m ${mountpoint} > crdb.out 2>&1
+	./createdb_mssql_mnt.sh -m "${mountpoint}" > crdb.out 2>&1
 
-	./update_temp_mnt.sh -m ${mountpoint} > upd_tmp.out 2>&1
+	./update_temp_mnt.sh -m "${mountpoint}" > upd_tmp.out 2>&1
 }
 
 install_mariadb()
@@ -92,33 +92,33 @@ install_mariadb()
 	#
 	# Configure things in and mount the appropriate item.
 	#
-	cd /usr/local/HammerDB
+	cd /usr/local/HammerDB || fatal "Cannot cd /usr/local/hammerdb"
 	cp -R  /tmp/hammerdb-tpcc/mariadb/* .
 
 	#
 	# Clean up any residual stuff and set up the directories
 	#
-	rm -rf ${mountpoint}/mysql/* ${log_mount_point}/mysql/log
-	mkdir -p ${mountpoint}/mysql/data
-	chown -R mysql:mysql ${mountpoint}/mysql
-        mkdir -p ${log_mount_point}/mysql/log
-        chown -R mysql:mysql ${log_mount_point}/mysql
+	rm -rf "${mountpoint}"/mysql/* "${log_mount_point}"/mysql/log
+	mkdir -p "${mountpoint}"/mysql/data
+	chown -R mysql:mysql "${mountpoint}"/mysql
+        mkdir -p "${log_mount_point}"/mysql/log
+        chown -R mysql:mysql "${log_mount_point}"/mysql
 
 
-	totmem=`cat /proc/meminfo | grep "MemTotal:" | awk '{print $2}'`
+	totmem=$(grep MemTotal /proc/meminfo | awk '{print $2}')
 	#
 	# Updating the value of buffer_pool_size based on available memory
 	# Setting bufferpool to half of physical memory if memory is less than 128G else set to 64G
 	#
-	totmem_BP=`expr $totmem / 1024`
-	totmem_BP=`expr $totmem_BP / 2`
+	totmem_BP=$((totmem / 1024))
+	totmem_BP=$((totmem_BP / 2))
 
 	#
 	# Configure the mariadb config file with mountpoint and bufferpool
 	#
 
 	sed -i "s+^datadir=.*+datadir=${mountpoint}\/mysql\/data+" my.cnf
-	if [ $totmem_BP -lt 64000 ]; then
+	if ((totmem_BP << 64000 )); then
    		sed -i "s/^innodb_buffer_pool_size=.*/innodb_buffer_pool_size=${totmem_BP}M/" my.cnf
 	else
    		sed -i "s/^innodb_buffer_pool_size=.*/innodb_buffer_pool_size=64000M/" my.cnf
@@ -148,35 +148,35 @@ install_postgres()
 	#
 	dnf -y install postgresql.x86_64 postgresql-contrib.x86_64 postgresql-server.x86_64 glibc-langpack-en libpq
 
-	cd /usr/local/HammerDB
+	cd /usr/local/HammerDB || fatal "Cannot cd /usr/local/hammerdb"
 	cp -R /tmp/hammerdb-tpcc/postgres/* .
 
 	rm -rf /var/lib/pgsql/data
-	rm -rf ${mountpoint}/postgres_data
+	rm -rf "${mountpoint}"/postgres_data
 
-	mkdir -p ${mountpoint}/postgres_data
-	ln -sf ${mountpoint}/postgres_data /var/lib/pgsql/data
-	chmod 700 ${mountpoint}/postgres_data
-	chown -R postgres:postgres ${mountpoint}/postgres_data
-        mkdir -p ${log_mount_point}/postgres_log
-        chown -R mysql:mysql ${log_mount_point}/postgres_log
+	mkdir -p "${mountpoint}"/postgres_data
+	ln -sf "${mountpoint}"/postgres_data /var/lib/pgsql/data
+	chmod 700 "${mountpoint}"/postgres_data
+	chown -R postgres:postgres "${mountpoint}"/postgres_data
+        mkdir -p "${log_mount_point}"/postgres_log
+        chown -R mysql:mysql "${log_mount_point}"/postgres_log
 
 	postgresql-setup initdb
 	sleep 10
-	mv /var/lib/pgsql/data/pg_wal ${log_mount_point}/postgres_log
-	ln -sf ${log_mount_point}/postgres_log/pg_wal /var/lib/pgsql/data/pg_wal
+	mv /var/lib/pgsql/data/pg_wal "${log_mount_point}"/postgres_log
+	ln -sf "${log_mount_point}"/postgres_log/pg_wal /var/lib/pgsql/data/pg_wal
 
-	totmem=`cat /proc/meminfo |grep "MemTotal:" | awk '{print $2}'`
+	totmem=$(grep MemTotal /proc/meminfo | awk '{print $2}')
 
 	#
 	# Change shared_buffer size based on available memory
 	#
-	totmem_MB=`expr $totmem / 1024`
-	totmem_BP=`expr $totmem_MB / 2`   # Buffer pool is half of physical memory
+	totmem_MB=$((totmem / 1024))
+	totmem_BP=$((totmem_MB / 2))   # Buffer pool is half of physical memory
 	#
 	# IF total memory is more than 128G then bufferpool is set to 64G else set to half of physical memory
 	#
-	if [ ${totmem_BP} -lt 64000 ]; then
+	if ((totmem_BP < 65000)) ; then
    		sed -i "s/^shared_buffers =.*/shared_buffers = ${totmem_BP}MB/" postgresql.conf
 	else
 	   	sed -i "s/^shared_buffers =.*/shared_buffers = 64000MB/" postgresql.conf
@@ -194,7 +194,8 @@ install_postgres()
 
 usage()
 {
-  echo "Usage:
+        cat <<'EOF'
+Usage:
         ./install-script [-h] [-d disk name] [-m mount point] [-t dbtype]
 
         Usage:
@@ -207,51 +208,37 @@ usage()
        Examples:
         ./install-script -d '/dev/sdb' 
         ./install-script -d '/perf1' 
-  "
+EOF
+        exit
+}
+
+fatal()
+{
+	echo "$*"
+	exit 1
 }
 
 #
 # If we did not pass any arguments, flag it.
 #
 if [ $# -eq 0 ]; then
-    usage;
-    exit;
+    usage
 fi
 
-while [ $# -gt 0 ]
-do
-	case $1 in
-        	-h)
-			usage;
-			exit;
-		;;
-        	-d)
-			disks=$2
-			shift 2
-		;;
-		-M)
-			log_mount_point=$2
-			shift 2
-		;;
-		-m)
-			mountpoint=$2
-			shift 2
-		;;
-		-t) 
-			db_type=$2
-			shift 2
-		;;
-		*)
-			usage;
-			exit;
-		;;
+while getopts 'hd:M:m:t:' opt ; do
+	case "$opt" in
+		d) disks="$OPTARG" ;;
+		M) log_mount_point="$OPTARG" ;;
+		m) mountpoint="$OPTARG" ;;
+		t) db_type="$OPTARG" ;;
+		h) usage ;;
+		*) usage ;;
 	esac
 done
 
-if [[ $db_type == "none" ]]; then
-	echo You need to designate the db type.
+if [[ -z "$db_type" ]]; then
+	echo "You need to designate the db type."
 	usage
-	exit
 fi
 
 #
@@ -267,13 +254,14 @@ curl -k -o /tmp/hammerdb-tpcc.tar https://people.redhat.com/srao/Hammerdb-Kit/ha
 #
 # Install the hammerdb
 #
-cd /tmp
+cd /tmp || fatal "Cannot cd /tmp"
 tar xf hammerdb-tpcc.tar
-cd /tmp/hammerdb-tpcc/Hammerdb
+cd /tmp/hammerdb-tpcc/Hammerdb || fatal "Cannot cd to hammerdb package directory!"
 unset DISPLAY
-echo "y" > input
-echo "/usr/local/HammerDB" >> input
-./HammerDB-3.2-Linux-x86-64-Install < input
+./HammerDB-3.2-Linux-x86-64-Install <<'EOF'
+y
+/usr/local/HammerDB
+EOF
 
 #
 # Shutdown all running instances
@@ -285,33 +273,30 @@ systemctl stop mariadb
 #
 # Create filestems and mount if required
 #
-if [[ $mountpoint == *"none"* ]]; then
+if [[ -z "$mountpoint" ]]; then
+	if [[ -z "$disks" ]] ; then
+		echo "Disk must be specified if -m is not used"
+		usage
+	fi
 	echo "using disk option"
 	umount /perf1
-	mkfs.xfs -f ${disks}
+	mkfs.xfs -f "${disks}"
 	mkdir -p /perf1
-	mount ${disks} /perf1
+	mount "${disks}" /perf1
 	mountpoint="/perf1"
 else
 	echo "using mountpoint option"
-	echo ${mountpoint}
+	echo "${mountpoint}"
 fi
 
-if [[ $log_mount_point == "none" ]]; then
-	log_mount_point=${mountpoint}
-fi
-if [[ $db_type == "mssql" ]]; then
-	install_mssql
-	exit
-fi
+log_mount_point=${log_mount_point:-$mountpoint}
+case "$db_type" in
+	mssql) install_mssql ;;
+	mariadb) install_mariadb ;;
+	postgres) install_postgres ;;
+	*) echo "Unknown database $db_type specified"; usage ;;
+esac
 
-if [[ $db_type == "mariadb" ]]; then
-	install_mariadb
-	exit
-fi
-
-if [[ $db_type == "postgres" ]]; then
-	install_postgres
-	exit
-fi
-
+# Local Variables:
+# sh-indentation: 8
+# End:
