Fix some more broken paths

diff --git a/hammerdb/install-script b/hammerdb/install-script
--- a/hammerdb/install-script
+++ b/hammerdb/install-script
@@ -26,6 +26,7 @@ db_type=
 log_mount_point=
 install_packages=1
 instdir=/var/local/HammerDB
+srcdir=/opt/HammerDB
 
 install_mssql()
 {
@@ -40,8 +41,8 @@ install_mssql()
 	systemctl stop mssql-server
 	# shellcheck disable=SC2016
 	echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
-	cd "$instdir" || fatal "Cannot cd /usr/local/hammerdb"
-	cp -R  "${instdir}"/hammerdb-tpcc/mssql/* .
+	cd "$srcdir" || fatal "Cannot cd /usr/local/hammerdb"
+	cp -R  "${srcdir}"/hammerdb-tpcc/mssql/* .
 
 	rm -rf "${mountpoint}"/mssql_data/
 	mkdir -p "${mountpoint}"/mssql_data
@@ -97,8 +98,8 @@ install_mariadb()
 	#
 	# Configure things in and mount the appropriate item.
 	#
-	cd "$instdir" || fatal "Cannot cd /usr/local/hammerdb"
-	cp -R  "${instdir}"/tmp/hammerdb-tpcc/mariadb/* .
+	cd "$srcdir" || fatal "Cannot cd /usr/local/hammerdb"
+	cp -R  "${srcdir}"/tmp/hammerdb-tpcc/mariadb/* .
 
 	#
 	# Clean up any residual stuff and set up the directories
@@ -155,8 +156,8 @@ install_postgres()
 			      libpq
 	fi
 	systemctl stop postgresql.service
-	cd "$instdir" || fatal "Cannot cd /usr/local/hammerdb"
-	cp -R "${instdir}"/hammerdb-tpcc/postgres/* .
+	cd "$srcdir" || fatal "Cannot cd /usr/local/hammerdb"
+	cp -R "${srcdir}"/hammerdb-tpcc/postgres/* .
 
 	rm -rf /var/lib/pgsql/data
 	rm -rf "${mountpoint}"/postgres_data
